config/routes.rb
Rails.application.routes.draw do
  namespace :models do
    get 'comments/get_from_article'
    get 'comments/create'
    get 'comments/delete'
    get 'comments/edit'
  end
  #map.connect '/:action', :controller => "main", :action => /index|categories|search/
  # Index/Root
  root 'main#index'
  # Categories
  get '/categories', to: 'main#categories'
  # Categories
  get '/search', to: 'main#search'
  # Account stuff
  # Login
  get '/login', to: 'account#login'
  post '/login', to: 'account#login'
  # Logout
  get '/logout', to: 'account#logout'
  # Register
  get '/register', to: 'account#register'
  post '/register', to: 'account#register'
  # User settings
  get '/settings', to: 'account#settings'
  post '/settings', to: 'account#settings'
  # Show article
  get '/article/:id', to: 'main#article'
  # Show category
  get '/category/:id', to: 'main#category'
  #

  # Admin panel
  get '/admin', to: 'admin#index'
  post '/admin', to: 'admin#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :sidebar
  def index
    # TODO: Implement pagination
    @articles = Article.all_published.order(:publish_by).page(1).per(10)
    puts @articles.inspect
  end

  def categories
    # TODO: Implement pagination
    @categories = Category.all
  end

  def search
    if params[:query].present?
      # Implements fuzzy search
      # TODO: Implement pagination
      @articles = Article.where('(publish_by is not null and publish_by <= :now) AND (title LIKE :search OR content LIKE :search)', now: DateTime.now, search: params[:query])
    end
  end

  def category
    # TODO: Implement published only querying
    unless params[:id].present?
      redirect_back_or_to :categories
      return
    end

    @category = Category.find_by id: params[:id]
    unless @category.present?
      redirect_back_or_to :categories
    end
  end

  def article
    unless params[:id].present?
      redirect_back_or_to :root
      return
    end

    @article = Article.find_by id: params[:id]
    unless @article.present?
      redirect_back_or_to :root
    end
  end

  protected

  def sidebar
    @sidebar_comments
    @sidebar_categories
  end

  # Also sets the valid current page
  def load_pagination(page: 1, max_page: 1)

  end
end

app/helpers/main_helper.rb
module MainHelper
  def active_class(path)
    request.path == path ? 'active' : ''
  end

  def list_article_categories(categories: nil, capitalise: true)
    if categories.present?
      category_names = []

    end
  end


end

app/views/layouts/main/_footer.html.erb
<footer class="text-center">
  <footer class="text-center bg-dark">
    <div class="container text-white py-4 py-lg-5">
      <p class="mb-0">Copyright © 2023 Alvin Alvarado</p>
      <sup class="fw-light">
        This is a free and open source software licensed under the <a class="fw-light" href="https://www.gnu.org/licenses/agpl-3.0.en.html" rel="license">GNU Afferro General Public License</a> with the source code being hosted in <a class="fw-light" href="https://github.com/striczkof/bruh-news">this repository</a>. You can redistribute it and/or modify it under the terms of the AGPLv3 as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
      </sup>
    </div>
  </footer>
</footer>

app/views/layouts/main/_navbar.html.erb
<nav class="navbar navbar-expand-md sticky-top bg-dark py-3" data-bs-theme="dark">
  <div class="container-fluid">
    <%= render partial: 'layouts/brand' %>
    <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1">
      <span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navcol-1">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to 'Categories', categories_path, class: 'nav-link ' + active_class(categories_path) %>
        </li>
        <li class="nav-item">
          <%= link_to 'Search', search_path, class: 'nav-link ' + active_class(search_path) %>
        </li>
        <% if @current_user.present? && @current_user.is_admin %>
          <li class="nav-item">
            <%= link_to 'Admin Panel', admin_path, class: 'nav-link ' + active_class(admin_path) %>
          </li>
        <% end %>
      </ul>
      <div class="d-md-none my-2">
        <div class="d-md-none my-2">
          <p class="text-white my-auto">
            Hi <%= get_name %>!
            <span class="float-end">
              <% if @current_user.present? %>
                <%= link_to 'User settings', settings_path %>&nbsp;|&nbsp;<%= link_to 'Logout', logout_path %>
              <% else %>
                <%= link_to 'Login', login_path %>&nbsp;|&nbsp;<%= link_to 'Register', register_path %>
              <% end %>
            </span>
          </p>
        </div>
      </div>
    </div>
    <div class="d-none d-md-block">
      <p class="text-white my-auto">
        Hi <%= get_name %>!&nbsp;
        <span>
          <% if @current_user.present? %>
            <%= link_to 'User settings', settings_path %>&nbsp;|&nbsp;<%= link_to 'Logout', logout_path %>
          <% else %>
            <%= link_to 'Login', login_path %>&nbsp;|&nbsp;<%= link_to 'Register', register_path %>
          <% end %>
        </span>
      </p>
    </div>
  </div>
</nav>

app/views/layouts/main/_pagination.html.erb
<nav class="d-flex d-xl-flex justify-content-center justify-content-xl-center">
  <ul class="pagination">
    <li class="page-item disabled">
      <a class="page-link" aria-label="Previous" href="#">
        <span aria-hidden="true">«</span>
      </a>
    </li>
    <li class="page-item disabled">
      <a class="page-link" aria-label="Previous" href="#">
        <span aria-hidden="true">«</span>
      </a>
    </li>
    <li class="page-item active">
      <a class="page-link" href="#">1</a>
    </li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" aria-label="Next" href="#"><span aria-hidden="true">»</span></a></li>
    <li class="page-item"><a class="page-link" aria-label="Next" href="#"><span aria-hidden="true">»</span></a></li>
  </ul>
</nav>

app/views/layouts/main/_sidebar.html.erb
<div class="col-md-4" id="main-sidebar">
  <div class="vstack">
    <div class="card">
      <div class="card-header">
        <h5 class="mb-0">Latest comments</h5>
      </div>
      <div class="card-body">
        <% if @sidebar_comments.present? %>
          <ul class="list-group">
            <li class="list-group-item">
              <figure>
                <blockquote class="blockquote">
                  <p class="mb-0">Let's give Ukraine Minuteman III ICBMs so this war ends now. Also I love F35chan</p>
                </blockquote>
                <figcaption class="blockquote-footer text-truncate">Planefucker on&nbsp;<a href="/articles/show"><span style="color: rgba(var(--bs-link-color-rgb),var(--bs-link-opacity,1));">Ukraine receives the battleship USS Texas from the United States</span></a></figcaption>
              </figure>
            </li>
            <li class="list-group-item">
              <figure>
                <blockquote class="blockquote">
                  <p class="mb-0">SLAVA ROSSII Z</p>
                </blockquote>
                <figcaption class="blockquote-footer text-truncate">Vatnik on&nbsp;<a href="/articles/show">Another L for Russia:&nbsp;<span style="color: rgb(33, 37, 41);">Russia drops 300 VDV paratroopers to the Pacific, looking for Harold Holt</span></a></figcaption>
              </figure>
            </li>
            <li class="list-group-item">
              <figure>
                <blockquote class="blockquote">
                  <p class="text-truncate mb-0">I love trains</p>
                </blockquote>
                <figcaption class="blockquote-footer text-truncate">Conductor on&nbsp;<a href="/articles/show">Conductor found fornicating with locomotives</a></figcaption>
              </figure>
            </li>
          </ul>
        <% else %>
          <p>No comments to display, or not implemented even :(</p>
        <% end %>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        <h5 class="mb-0">Latest articles in categories</h5>
      </div>
      <div class="card-body">
        <% if @sidebar_categories.present? %>
          <ul>
            <li>&nbsp;<a href="#"><span style="color: rgba(var(--bs-link-color-rgb),var(--bs-link-opacity,1));">Ukraine receives the battleship USS Texas from the United States</span></a>&nbsp;in&nbsp;<a href="#">Conflicts</a></li>
            <li>&nbsp;<a href="#"><span style="color: rgba(var(--bs-link-color-rgb),var(--bs-link-opacity,1));">Conductor found fornicating with locomotives</span></a>&nbsp;in&nbsp;<a href="#">Local</a></li>
            <li>&nbsp;<a href="#">'I have figured out the final solution' exclaims an Austrian painter</a>&nbsp;in&nbsp;<a href="#">Nature</a></li>
          </ul>
        <% else %>
          <p>No articles in categories to display, or not implemented even :(</p>
        <% end %>
      </div>
    </div>
  </div>
</div>